### ISSUE TITLE
All features must have a class ID

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#1]
- Make features class_id column non nullable
- Add to class column 3 new classes:
  - Survival Time
  - Survival Status
  - Miscellaneous
- Give the following features these classes:
98	20	CTA Score	       Miscellaneous
99	71	OS	                       Survival Status
100	72	OS Time	               Survival Time
101	73	PFI	                       Survival Status
102	74	PFI Time	               Survival Time
103	99	Total TCR reads     Miscellaneous

**Comment by megankuhn** [comment]
Captured in pivotal:

- https://www.pivotaltracker.com/story/show/170629885
- https://www.pivotaltracker.com/story/show/170836493
- https://www.pivotaltracker.com/story/show/170836499

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
