### ISSUE TITLE
No genes of extra cellular network type

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#11]
This query produces an empty table. It appears that no genes are "tagged" as extra cellular network at the moment.

create_connection("gene_types") %>% 
            dplyr::filter(name == "extra_cellular_network") %>%
            dplyr::select(type_id = id) %>% 
            dplyr::inner_join(
                create_connection("genes_to_types"),
                by = "type_id"
            )

**Comment by megankuhn** [comment]
captured in pivotal: https://www.pivotaltracker.com/story/show/170734742

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
