### ISSUE TITLE
Edges table column name

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#12]
I think we wanted to call ratio score something specific to it being in the extracellular network, like ecn score.

**Comment by jonryser** [comment]
I believe we did talk about his and decided to call that column "score". Also in the nodes table to call the value "score".

**Comment by megankuhn** [comment]
Captured in pivotal: https://www.pivotaltracker.com/story/show/170836975

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
