### ISSUE TITLE
Clinical data in patients table

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#13]
Race ethnicity and gender are currently NA in the samples table, and should be in the patients table.

I think we want to remove things form the features table that have the clinical class and move them to the patients table as well. This includes things like Age and Weight.

**Comment by megankuhn** [comment]
captured in pivotal: https://www.pivotaltracker.com/story/show/170837017

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
