### ISSUE TITLE
gene mutations table

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#15]
We should take status and mutation code out of genes_to_samples and put in a new table

"mutations_to_samples" with the following columns

sample_id   gene_id   mutation_code_id   status  type

genes will be able to have more than  one mutation_code_id with a status value per code.

I'm not 100% sold on type, but we'll need to be able to identify all the driver genes and mutation types

**Comment by megankuhn** [comment]
confirmed with andrew and james:

genes to samples table (don't have mutations, has RNA seq)
genes to samples with mutations table (no RNA seq)

**Comment by megankuhn** [comment]
captured in pivotal: 
- https://www.pivotaltracker.com/story/show/171028998
- https://www.pivotaltracker.com/story/show/171028984

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
