### ISSUE TITLE
Extracellular network gene loaded

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#2]
Genes from

https://github.com/CRI-iAtlas/shiny-iatlas/blob/cytokine_network/data/network/network_node_label_friendly.feather

loaded into Genes table

- The Obj column should be the hgnc column
- The FriendlyName column is either the canconical or display name
- The type column should be the same as the super category column in genes.
- There are a lot of genes in the file that aren't in the genes, or genes to samples tables, and those tables will need to have these in them
- All genes not in genes_to_samples will need RNASeq expression data added.

**Comment by megankuhn** [comment]
Items 1-4 captured in pivotal: https://www.pivotaltracker.com/story/show/170734742

**Comment by megankuhn** [comment]
item 5 captured in pivotal: https://www.pivotaltracker.com/story/show/170836641

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
