### ISSUE TITLE
All gene expression added

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#3]

**Comment by megankuhn** [comment]
@andrewelamb  - can you add more detail? which gene expressions are missing?

**Comment by andrewelamb** [comment]
```
"SELECT COUNT( DISTINCT gene_id) AS n FROM genes_to_samples WHERE rna_seq_expr IS NOT NULL" %>% 
+     dplyr::sql() %>% 
+     .GlobalEnv$perform_query("build driver results table")
Time taken to perfrom query build driver results table: 2.461 sec elapsed
# A tibble: 1 x 1
      n
  <dbl>
1   434
```

The file EBPlusPlusAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv from https://gdc.cancer.gov/node/905/ should have at least 10,000 genes in it, I think ~20,000 is what I am expecting.

**Comment by megankuhn** [comment]
Per discussion 1/31 - let's plan for this post v1 release. In the meantime, this has been captured in pivotal: https://www.pivotaltracker.com/story/show/171028914
