### ISSUE TITLE
Add a mutation type table

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#30]
This wold be similar to the genes type table. Right now there are only driver mutations, but we will likely add other mutations and we will need to be able to pull out certain types of mutations (beyond the mutation code). 

This could possibly be accomplished by using the tags table to tags gene/mutation combinations.

**Comment by andrewelamb** [comment]
- Replace genes_samples_mutations with samples_to_mutations with the following columns:
sample_id, mutation_id, status

- Add new table mutations with the following columns: 
id, gene_id, mutation_code_id, mutation_type_id

- Add new table mutation types with the following columns:
id, name

- Remove mutation_codes_to_gene types
- Remove driver mutations as a type from gene_types

**Comment by jonryser** [comment]
This has been completed per Pivotal #171731186
