### ISSUE TITLE
Resolve alternate gene names

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#4]
This has to do with the current gene name sin the caconical and display column. This should resolve the gene names in driver mutation file.

**Comment by andrewelamb** [comment]
Get rid of canonical and display names in the table.
friendly_name will be from Immunomodulators google sheet
io_cancer_landscape column will be from Io targets google sheet friendly name

**Comment by megankuhn** [comment]
captured in pivotal:

- https://www.pivotaltracker.com/story/show/170709926
- https://www.pivotaltracker.com/story/show/170709694

**Comment by megankuhn** [comment]
This is completed and merged into the working feature branch
