### ISSUE TITLE
Resolve TCGA tissue ids

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#6]
The tilmaps module currently uses a tissue id to form a link to TIL image for some samples.

**Comment by andrewelamb** [comment]
TCGA-05-4410-01Z-00-DX1 for example is actually the id of a slide for patient TCGA-05-4410.

We may want to add a new table called slides that look like:

sample_id          slide_id                                    type
TCGA-05-4410  TCGA-05-4410-01Z-00-DX1   E&H

**Comment by megankuhn** [comment]
captured in pivotal, tasks below:

- https://www.pivotaltracker.com/story/show/170708868
- https://www.pivotaltracker.com/story/show/170708888
- https://www.pivotaltracker.com/story/show/170709019
- https://www.pivotaltracker.com/story/show/170709062

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
