### ISSUE TITLE
Add copy number results table

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#7]
cols(
 group = col_character(),
 Mean_Norm = col_double(),
 Mean_CNV = col_double(),
 t = col_double(),
 pvalue = col_double(),
 neg_log10_pvalue = col_double(),
 metric = col_character(),
 direction = col_character(),
 gene = col_character(),
)

**Comment by andrewelamb** [comment]
This needs final results table from @Gibbsdavidl

**Comment by jonryser** [comment]
Columns will be:
- "tag_id" - integer
- "gene_id" - integer
- "feature_id" - integer
- "mean_normal" - numeric
- "mean_cnv" - numeric
- "t_stat" - numeric
- "direction" - enum of ["Amp", "Del"]
- "p_value" - numeric
- "log10_p_value" - numeric

**Comment by Gibbsdavidl** [comment]
Is there going to be a gene lookup table, to use that gene_id with?

**Comment by andrewelamb** [comment]
Yep, take a look at the bottom of the page here:

https://github.com/CRI-iAtlas/iatlas-data/tree/staging/data_model
