### ISSUE TITLE
Remake driver results file

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-data#8]
File must match db table with genes, groups and features that match other tables

**Comment by andrewelamb** [comment]
The gene names in the driver mutations files look like:

 "RQCD1 P131L" "TP53 Q136*"  "APC R213*"   "FGFR2"       "KEAP1 (OM)" 

RQCD1 P131L is actually two pieces of information.

RQCD1 is the hgnc symbol name
P131L is information about the mutation. We would like to include this in the data model as well.
(OM) should be Oncogenic Mutation in the database
We are still deciding what to include if blank such as FGFR2 above. Poissibilities include (Null or "Non silent")

**Comment by megankuhn** [comment]
captured in pivotal:

- https://www.pivotaltracker.com/story/show/170709338
- https://www.pivotaltracker.com/story/show/170709498
- https://www.pivotaltracker.com/story/show/170709588

**Comment by megankuhn** [comment]
This has been completed and merged into working feature branch
